### PR TITLE
Archived Board

### PR DESCRIPTION
**Pull request by Rolo123y**
Board called 'Archived'

User can only view this board and it will be used to store
deleted/archived tasks in the future.

### CODE REVIEW

**Comment by MayyarAA** [comment]
Hello,

There maybe a better solution then this approach of creating a new board for all users, which will require a large amount of memory allocation and data storage.

We can try to create a page that utilizes a select statement with multiple inner join queries to find archived tasks.

**Review by MayyarAA — COMMENTED** [review]
There maybe a better solution lets discuss on a video chat

**Comment by MayyarAA** [comment]
Hello,

There maybe a better solution then this approach of creating a new board for all users, which will require a large amount of memory allocation and data storage.

We can try to create a page that utilizes a select statement with multiple inner join queries to find archived tasks.

**Review by MayyarAA — CHANGES_REQUESTED** [review]
Hello,

There maybe a better solution then this approach of creating a new board for all users, which will require a large amount of memory allocation and data storage.

We can try to create a page that utilizes a select statement with multiple inner join queries to find archived tasks.

**Comment by Rolo123y** [comment]
good idea! my initial thought was to initialize an Archive board and place all the deleted tasks in this board as part of 1 list. But your method of having a separate page is much simpler.

**Comment by Rolo123y** [comment]
The new additions are:
1. removed the previous Archived board implementation
2. Added a file named ArchivePage.php which houses the archive UI and logic

**Comment by Rolo123y** [comment]
This change is not 100% complete. As of now, users can still delete tasks that are in the archived board which is not what we want.

**Comment by gaurav613** [comment]
I'm not sure, but this may have some relation to #58 - since the delete task button is routing the user to an older version of the board, according to the latest version of main.

**Review by MayyarAA — APPROVED** [review]

**Pull request merged**
